version: "3"
services:
  db:
    image : mysql:5.6
    restart: always
    ports: 
      - 3307:3306
    volumes:
      - /home/mysql5.6:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : 123456
      TZ : Asia/Shanghai
    container_name: mysql

  redis:
    image: redis:2.8
    restart: always
    command: redis-server --requirepass "123456"
    ports: 
      - 6380:6379
    volumes:
      - /home/redis3:/data
    container_name: redis

  fastdfs:
    image: meiko/fastdfs-single:5.11
    restart: always
    container_name: fastdfs
    environment:
    # nginx服务端口
      - WEB_PORT=8888
    # docker所在主机的IP地址
      - IP=172.17.0.1
    ports: 
      - 8888:8888
    volumes:
    # 将本地目录映射到docker容器内的fastdfs数据存储目录，将fastdfs文件存储到主机上，以免每次重建docker容器，之前存储的文件就丢失了。
      - /home/fastdfs:/var/local/fdfs
    # 使docker具有root权限以读写主机上的目录
    privileged: true
    # 网络模式为host，即直接使用主机的网络接口
    network_mode: "host"
